Theoretical Questions:   

word link : https://1drv.ms/w/c/690b3368af1a3158/EVFqR7Pa5RdJih3bmN3dx18BspZZF5WJYRed_EcVJOEU4A?e=0BdYXb

#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, (3, 3))

# Interchange the rows and columns
interchanged_arr = arr.T

# Print the original and interchanged arrays
print("Original array:")
print(arr)
print("\nInterchanged array:")
print(interchanged_arr)


Original array:
[[77 47 55]
 [59 38 87]
 [30 63 48]]

Interchanged array:
[[77 59 30]
 [47 38 63]
 [55 87 48]]


# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
arr = np.arange(10, dtype=int)

# Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)

# Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)

# Print the arrays
print("1D Array:")
print(arr)
print("\n2x5 Array:")
print(arr_2x5)
print("\n5x2 Array:")
print(arr_5x2)

1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
import numpy as np

# Create a 4x4 NumPy array with random float values
arr = np.random.rand(4, 4)

# Add a border of zeros around the array
border_width = 1
arr_with_border = np.pad(arr, pad_width=border_width, mode='constant', constant_values=0)

# Print the original and the array with the border
print("Original array:")
print(arr)
print("\nArray with border of zeros:")
print(arr_with_border)


Original array:
[[0.30484734 0.22252817 0.74813581 0.90840431]
 [0.02586078 0.55125005 0.54157454 0.16467347]
 [0.95273699 0.86310729 0.53726894 0.20438526]
 [0.86705967 0.28318723 0.69967665 0.9660094 ]]

Array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.30484734 0.22252817 0.74813581 0.90840431 0.        ]
 [0.         0.02586078 0.55125005 0.54157454 0.16467347 0.        ]
 [0.         0.95273699 0.86310729 0.53726894 0.20438526 0.        ]
 [0.         0.86705967 0.28318723 0.69967665 0.9660094  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)

# Print the array
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [5]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations to each element
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

# Print the original and transformed arrays
print("Original array:")
print(arr)
print("\nUppercase array:")
print(uppercase_arr)
print("\nLowercase array:")
print(lowercase_arr)
print("\nTitlecase array:")
print(titlecase_arr)



Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [6]:
import  numpy as np

# Generate a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Print the spaced words
print(spaced_words)

['p y t h o n' 'n u m p y' 'p a n d a s']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [7]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Perform element-wise addition
addition_result = np.add(arr1, arr2)

# Perform element-wise subtraction
subtraction_result = np.subtract(arr1, arr2)

# Perform element-wise multiplication
multiplication_result = np.multiply(arr1, arr2)

# Perform element-wise division
division_result = np.divide(arr1, arr2)

# Print the results
print("Addition Result:")
print(addition_result)
print("\nSubtraction Result:")
print(subtraction_result)
print("\nMultiplication Result:")
print(multiplication_result)
print("\nDivision Result:")
print(division_result)

Addition Result:
[[ 6  8]
 [10 12]]

Subtraction Result:
[[-4 -4]
 [-4 -4]]

Multiplication Result:
[[ 5 12]
 [21 32]]

Division Result:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the identity matrix and the diagonal elements
print("Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [12]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, size=100)
print(arr)

# prime number in this array
prime_numbers = []
for num in arr:
    if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                break
        else:
            prime_numbers.append(num)


print("prime number of above 100 random number is : ", prime_numbers)





[ 95 953 852 541 870 869   5 858 725 350 733 264 936 978 540 369 482 456
 453 869 306 822 917 768 544 449 598 586 961 996 111  50 707 701 594 577
 661 765 523 454  68 280 731 147 475 848 752 528  41 600 434  97 163 101
 289 310 378 701  52 240 526 605 470 663 732 880 461 777  13 244 968 951
 275 230 416 513 104 603  68 245   6 932 798 960 575 824 889 549 345 494
 124 167 538 197 154 476 108 791 299 927]
prime number of above 100 random number is :  [953, 541, 5, 733, 449, 701, 577, 661, 523, 41, 97, 163, 101, 701, 461, 13, 167, 197]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [13]:
import numpy as np

# Step 1: Create the temperature data for a month (30 days)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.randint(0, 35, size=30)  # Random temperatures between 0 and 34

# Step 2: Reshape the array into a 2D array where each row represents a week (5 rows, 6 days per week)
# Assuming 5 weeks for simplicity, with 6 days each
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily temperatures for the month:")
print(daily_temperatures)
print("\nWeekly temperatures (reshaped):")
print(weekly_temperatures)
print("\nWeekly averages:")
print(weekly_averages)


Daily temperatures for the month:
[ 0  3  3  9 19 21 23  6 24 24 12  1 23 24 17 25 13  8  9 20 16  5 15  0
 18 24 29 19 19 14]

Weekly temperatures (reshaped):
[[ 0  3  3  9 19 21]
 [23  6 24 24 12  1]
 [23 24 17 25 13  8]
 [ 9 20 16  5 15  0]
 [18 24 29 19 19 14]]

Weekly averages:
[ 9.16666667 15.         18.33333333 10.83333333 20.5       ]
